# -*- coding: utf-8 -*-
"""Preparcial2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G15plMP4b-uepI4LsHR3uqwvORIhQjLQ
"""

import csv

# Lista donde se guardan las transacciones
transacciones = []

# Datos del cajero
cajero = input("Ingrese el nombre o código del cajero: ")

# Solicitar y validar el tope
while True:
    try:
        tope = int(input("Ingrese el tope máximo de recaudo: "))

        if tope > 0:
            break
        else:
            print("El tope debe ser mayor que cero.")

    except ValueError:
        print("El tope debe ser un número entero.")


# Variables del turno
recaudoTotal = 0
motivoCierre = ""


# Función para mostrar las transacciones
def mostrarTransacciones():
    if len(transacciones) == 0:
        print("No hay transacciones registradas.")
    else:
        print("\n--- TRANSACCIONES ---")

        for transaccion in transacciones:
            print("ID:", transaccion["id"])
            print("Monto:", transaccion["monto"])
            print("---------------------")


# Menú principal
while True:

    print("\n         SISTEMA DE CAJA")
    print("Cajero:", cajero)
    print("Tope:", tope)
    print("Recaudo actual:", recaudoTotal)
    print()
    print("1. Registrar transacción")
    print("2. Ver transacciones")
    print("3. Editar transacción")
    print("4. Eliminar transacción")
    print("5. Guardar en CSV")
    print("6. Leer CSV")
    print("7. Finalizar turno")

    opcion = input("Seleccione una opción: ")


    # ==========================================
    # CREATE - Registrar una transacción
    # ==========================================

    if opcion == "1":

        entrada = input(
            "\nIngrese el monto del cliente "
            "o escriba FIN para terminar: "
        )

        # Finalizar por fin de cola
        if entrada.upper() == "FIN" or entrada == "0":
            motivoCierre = "Fin de cola"
            break

        try:
            monto = int(entrada)

        except ValueError:
            print("Monto rechazado. Debe ingresar un valor numérico.")
            continue

        # Rechazar números negativos
        if monto < 0:
            print("Monto rechazado. El valor debe ser mayor que cero.")
            continue

        # Crear ID para la transacción
        if len(transacciones) == 0:
            idTransaccion = 1
        else:
            idTransaccion = transacciones[-1]["id"] + 1

        # Crear la transacción
        nuevaTransaccion = {
            "id": idTransaccion,
            "monto": monto
        }

        # Agregar la transacción a la lista
        transacciones.append(nuevaTransaccion)

        # Actualizar el recaudo
        recaudoTotal = recaudoTotal + monto

        print("Transacción registrada correctamente.")
        print("Recaudo acumulado:", recaudoTotal)

        # Verificar el tope
        if recaudoTotal >= tope:

            motivoCierre = "Tope alcanzado"

            print("\n===================================")
            print("         CAJA SUSPENDIDA")
            print("===================================")
            print("Se alcanzó o superó el tope de recaudo.")
            print("Diríjase a tesorería.")

            break


    # ==========================================
    # READ - Mostrar transacciones
    # ==========================================

    elif opcion == "2":

        mostrarTransacciones()


    # ==========================================
    # UPDATE - Editar una transacción
    # ==========================================

    elif opcion == "3":

        if len(transacciones) == 0:
            print("No hay transacciones registradas.")

        else:

            mostrarTransacciones()

            try:
                idBuscar = int(input("Ingrese el ID de la transacción que desea editar: "))

                encontrado = False

                for transaccion in transacciones:

                    if transaccion["id"] == idBuscar:

                        nuevoMonto = int(
                            input("Ingrese el nuevo monto: ")
                        )

                        if nuevoMonto <= 0:
                            print("El monto debe ser mayor que cero.")
                        else:

                            # Cambiar el recaudo
                            recaudoTotal = recaudoTotal - transaccion["monto"]
                            recaudoTotal = recaudoTotal + nuevoMonto

                            # Actualizar el monto
                            transaccion["monto"] = nuevoMonto

                            print("Transacción actualizada correctamente.")

                        encontrado = True
                        break

                if encontrado == False:
                    print("No existe una transacción con ese ID.")

            except ValueError:
                print("Debe ingresar un número válido.")


    # ==========================================
    # DELETE - Eliminar una transacción
    # ==========================================

    elif opcion == "4":

        if len(transacciones) == 0:
            print("No hay transacciones registradas.")

        else:

            mostrarTransacciones()

            try:
                idEliminar = int(
                    input("Ingrese el ID de la transacción que desea eliminar: ")
                )

                encontrado = False

                for transaccion in transacciones:

                    if transaccion["id"] == idEliminar:

                        # Restar el monto eliminado
                        recaudoTotal = recaudoTotal - transaccion["monto"]

                        # Eliminar la transacción
                        transacciones.remove(transaccion)

                        print("Transacción eliminada correctamente.")

                        encontrado = True
                        break

                if encontrado == False:
                    print("No existe una transacción con ese ID.")

            except ValueError:
                print("Debe ingresar un número válido.")


    # ==========================================
    # GUARDAR EN CSV
    # ==========================================

    elif opcion == "5":

        with open("transaccionesCaja.csv", "w", newline="") as archivo:

            escritor = csv.writer(archivo)

            escritor.writerow([
                "ID",
                "Cajero",
                "Tope",
                "Monto"
            ])

            for transaccion in transacciones:

                escritor.writerow([
                    transaccion["id"],
                    cajero,
                    tope,
                    transaccion["monto"]
                ])

        print("Las transacciones fueron guardadas correctamente.")
        print("Archivo creado: transaccionesCaja.csv")


    # ==========================================
    # LEER CSV
    # ==========================================

    elif opcion == "6":

        try:

            with open("transaccionesCaja.csv", "r", newline="") as archivo:

                lector = csv.DictReader(archivo)

                print("\n--- DATOS DEL ARCHIVO CSV ---")

                for fila in lector:

                    print(
                        "ID:", fila["ID"],
                        "| Cajero:", fila["Cajero"],
                        "| Tope:", fila["Tope"],
                        "| Monto:", fila["Monto"]
                    )

        except FileNotFoundError:

            print("No existe todavía un archivo CSV.")


    # ==========================================
    # FINALIZAR TURNO
    # ==========================================

    elif opcion == "7":

        motivoCierre = "Fin de turno"
        break


    else:

        print("Opción no válida.")


# ==========================================
# REPORTE FINAL
# ==========================================

if len(transacciones) > 0:
    promedio = recaudoTotal / len(transacciones)
else:
    promedio = 0


print("\n===================================")
print("           REPORTE FINAL")
print("===================================")
print("Cajero:", cajero)
print("Tope asignado:", tope)
print("Transacciones procesadas:", len(transacciones))
print("Recaudo total:", recaudoTotal)
print("Promedio por transacción:", round(promedio, 2))
print("Motivo de cierre:", motivoCierre)
print("===================================")

