# -*- coding: utf-8 -*-
"""Preparcial2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G15plMP4b-uepI4LsHR3uqwvORIhQjLQ
"""

# Datos iniciales del turno

cajero = input("Ingrese el nombre o código del cajero: ")

# Validar el tope de recaudo
while True:
    try:
        tope = int(input("Ingrese el tope máximo de recaudo: "))

        if tope > 0:
            break
        else:
            print("El tope debe ser mayor que cero.")

    except ValueError:
        print("El tope debe ser un número entero.")


# Variables para controlar el recaudo
recaudoTotal = 0
transacciones = 0

print("\nInicio del turno")
print("Cajero:", cajero)
print("Tope asignado:", tope)


# Registro de clientes
while True:

    entrada = input("\nIngrese el monto del cliente o escriba FIN para terminar: ")

    # Finalizar el turno
    if entrada.upper() == "FIN" or entrada == "0":
        print("\nFin de la cola.")
        break

    # Validar que el monto sea un número
    try:
        monto = int(entrada)

        # Rechazar valores negativos
        if monto < 0:
            print("Monto rechazado. El valor debe ser mayor que cero.")
            continue

        # Acumular el monto
        recaudoTotal = recaudoTotal + monto
        transacciones = transacciones + 1

        print("Monto aceptado.")
        print("Recaudo acumulado:", recaudoTotal)

    except ValueError:
        print("Monto rechazado. Debe ingresar un valor numérico.")


print("\nTurno finalizado.")
print("Recaudo acumulado:", recaudoTotal)
print("Transacciones procesadas:", transacciones)

